SOURCES = [
    {
        "name": "Times of India Uttar Pradesh (Lucknow)",
        "language": "en",
        "type": "html",
        "url": "https://timesofindia.indiatimes.com/city/lucknow",
        "selector": "a[href*='/city/lucknow/'][href*='articleshow'], a[href*='/city/lucknow/']",
        "max_items": 20,
    },
    {
        "name": "Times of India Patna",
        "language": "en",
        "type": "html",
        "url": "https://timesofindia.indiatimes.com/city/patna",
        "selector": "a[href*='/city/patna/'][href*='articleshow'], a[href*='/city/patna/']",
        "max_items": 20,
    },
    {
        "name": "Times of India",
        "language": "en",
        "type": "rss",
        "url": "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms",
        "max_items": 20,
    },
    {
        "name": "The Hindu",
        "language": "en",
        "type": "rss",
        "url": "https://www.thehindu.com/news/national/feeder/default.rss",
        "max_items": 20,
    },
    {
        "name": "NDTV News",
        "language": "en",
        "type": "rss",
        "url": "https://feeds.feedburner.com/ndtvnews-top-stories",
        "max_items": 20,
    },
    {
        "name": "Hindustan Times",
        "language": "en",
        "type": "rss",
        "url": "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
        "max_items": 20,
    },
    {
        "name": "Jagran Hindi",
        "language": "hi",
        "type": "rss",
        "url": "https://rss.jagran.com/rss/news/national.xml",
        "max_items": 20,
    },
    {
        "name": "BBC News India",
        "language": "en",
        "type": "html",
        "url": "https://www.bbc.com/news/world/asia/india",
        "selector": "h2[data-testid='card-headline'], h2, a[href*='/news/world-asia-india']",
        "max_items": 15,
    },
    {
        "name": "Amar Ujala",
        "language": "hi",
        "type": "html",
        "url": "https://www.amarujala.com/india-news",
        "selector": "a[href^='/india-news/'], a[href^='/live/india-news/'], a[href^='/photo-gallery/india-news/']",
        "max_items": 15,
    },
    {
        "name": "Amar Ujala Bihar",
        "language": "hi",
        "type": "html",
        "url": "https://www.amarujala.com/bihar",
        "selector": "a[href*='/bihar/'], a[href*='bihar-news-']",
        "max_items": 20,
    },
    {
        "name": "Amar Ujala Uttar Pradesh",
        "language": "hi",
        "type": "html",
        "url": "https://www.amarujala.com/uttar-pradesh",
        "selector": "a[href*='/uttar-pradesh/'], a[href*='up-'], a[href*='/lucknow/'], a[href*='/varanasi/']",
        "max_items": 20,
    },
    {
        "name": "News18 Hindi",
        "language": "hi",
        "type": "html",
        "url": "https://hindi.news18.com/news/nation/",
        "selector": "a[href^='/news/nation/'][href$='.html'], a[href^='/news/business/'][href$='.html'], a[href^='/news/career/'][href$='.html'], a[href^='/news/dharm/'][href$='.html']",
        "max_items": 15,
    },
    {
        "name": "Live Hindustan Bihar",
        "language": "hi",
        "type": "html",
        "url": "https://www.livehindustan.com/bihar",
        "selector": "a[href*='/bihar/'], a[href*='/patna/'], a[href*='/muzaffarpur/'], a[href*='/bhagalpur/'], a[href*='/gaya/']",
        "max_items": 25,
    },
    {
        "name": "Live Hindustan Uttar Pradesh",
        "language": "hi",
        "type": "html",
        "url": "https://www.livehindustan.com/uttar-pradesh",
        "selector": "a[href*='/uttar-pradesh/'], a[href*='/lucknow/'], a[href*='/agra/'], a[href*='/gorakhpur/'], a[href*='/meerut/']",
        "max_items": 25,
    },
    {
        "name": "Dainik Jagran Bihar",
        "language": "hi",
        "type": "html",
        "url": "https://www.jagran.com/bihar",
        "selector": "a[href*='/bihar/'], a[href*='bihar-news'], a[href*='patna-city']",
        "max_items": 25,
    },
    {
        "name": "Dainik Jagran Uttar Pradesh",
        "language": "hi",
        "type": "html",
        "url": "https://www.jagran.com/uttar-pradesh",
        "selector": "a[href*='/uttar-pradesh/'], a[href*='lucknow-city'], a[href*='varanasi-city'], a[href*='kanpur-city']",
        "max_items": 25,
    },
    {
        "name": "Firstpost",
        "language": "en",
        "type": "html",
        "url": "https://www.firstpost.com/category/india",
        "selector": "a.en-ttl.latest_category_news, a.ctg-txt.latest_category_news, a[href*='/india/'][href$='.html'], a[href*='/explainers/'][href$='.html'], a[href*='/business/'][href$='.html']",
        "max_items": 15,
    },
]

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
]

SIMILARITY_THRESHOLD = 0.8
MAX_WORKERS = 5
TIMEOUT = 15
